version: '2'

services:
    load-balancer:
        depends_on:
          - sample-backend
        image: sample-lb
        ports:
            - 1080:80
        restart: always

    sample-backend:
        depends_on:
          - db
        image: sample-backend
        ports:
          - 8080:8080
        environment:
          - POSTGRES_HOST=db
        restart: always

    db:
        image: postgres:9.6
        restart: always
        volumes:
          - /tmp/sample-db-data:/var/lib/postgresql/data