version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - mvn-dependencies-{{ checksum "backend/pom.xml" }}
            - mvn-dependencies-
      - run: docker run -v /tmp/.m2:/root/.m2 -v `pwd`/backend:/app maven:3.5.3-jdk-8-alpine mvn -f /app/pom.xml package
      - save_cache:
          paths:
            - /tmp/.m2
          key: mvn-dependencies-{{ checksum "backend/pom.xml" }}
      - store_test_results:
          path: backend/target/surefire-reports
      - store_artifacts:
          path: backend/target/ci-test-0.0.1-SNAPSHOT.jar