version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - mvn-dependencies-1-{{ checksum "backend/pom.xml" }}
            - mvn-dependencies-1-
      - run: docker build -t maven-build-image -f build.Dockerfile .
      - run: mkdir -p $HOME/.m2 && chmod -R 777 $HOME/.m2
      - run: rm -rf backend/target && mkdir -p backend/target && chmod -R 777 backend/target
      - run: docker run --rm -v $HOME/.m2:/home/nonroot/.m2 -v `pwd`/backend/target:/build/target maven-build-image
      - save_cache:
          paths:
            - $HOME/.m2
          key: mvn-dependencies-1-{{ checksum "backend/pom.xml" }}
      - store_test_results:
          path: backend/target/surefire-reports
      - run: docker build -t sample-backend -t $REGISTRY_DOMAIN/sample-backend .
      - run: docker build -t sample-lb -t $REGISTRY_DOMAIN/sample-lb -f lb/Dockerfile --build-arg BACKEND_DOMAIN_VALUE=backend.sample.$DOMAIN ./lb
      - run: docker build -t sample-integration-test -f integration-test/Dockerfile --build-arg BACKEND_DOMAIN_VALUE=backend.sample.$DOMAIN integration-test/

  integration-test:
    machine: true
    steps:
      - run:
          name: Integration test with docker compose
          command: |
            { sleep 2 && docker-compose up -d; } & \
            docker-compose -f integration-test/lb/docker-compose.yml up --abort-on-container-exit || \
            { docker-compose logs && exit 1; }

  push-artifacts:
    machine: true
    steps:
      - run:
          name: Login to docker registry
          command: docker login --username registry_user --password $DOCKER_REGISTRY_PASSWORD $REGISTRY_DOMAIN
      - run:
          name: Push backend
          command: docker push $REGISTRY_DOMAIN/sample-backend
      - run:
          name: Push load balancer
          command: docker push $REGISTRY_DOMAIN/sample-lb

workflows:
  version: 2
  build_test_and_push_artifacts:
    jobs:
      - build
      - integration-test:
          requires:
            - build
      - push-artifacts:
          requires:
            - build
            - integration-test
          filters:
            branches:
              only: master