version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - mvn-dependencies-1-{{ checksum "backend/pom.xml" }}
            - mvn-dependencies-1-
      - run: docker build -t maven-build-image -f build.Dockerfile .
      - run: mkdir -p /tmp/.m2 && chmod -R 777 /tmp/.m2
      - run: rm -rf backend/target && mkdir -p backend/target && chmod -R 777 backend/target
      - run: docker run --rm -v /tmp/.m2:/home/nonroot/.m2 -v `pwd`/backend/target:/build/target maven-build-image
      - save_cache:
          paths:
            - /tmp/.m2
          key: mvn-dependencies-1-{{ checksum "backend/pom.xml" }}
      - store_test_results:
          path: backend/target/surefire-reports
      - run: docker build -t sample-backend .
      - run: printf "\n127.0.0.1    backend.sample.buyanov.ru" | sudo tee -a /etc/hosts
      - run: ./test-compose.sh